config/routes.rb
Designdidit::Application.routes.draw do
  root :to => "designs#index"
  match 'designs/tag/:id' => 'designs#tag', :as => :designs_by_tag

  resources :designs do
    collection do
      get 'what'
    end
  end
  

end

app/models/design.rb
class Design < ActiveRecord::Base
  acts_as_taggable
  attr_protected :approved
  
  validates_presence_of :description, :source_url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  # GET /designs
  # GET /designs.xml
  def index
    @design = Design.all.choice

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @designs }
    end
  end

  # GET /designs/1
  # GET /designs/1.xml
  def show
    @design = Design.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @design }
    end
  end
  
  def tag
    @designs = Design.find_tagged_with(params[:id])
  end

  # GET /designs/new
  # GET /designs/new.xml
  def new
    @design = Design.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @design }
    end
  end
  # 
  # # GET /designs/1/edit
  # def edit
  #   @design = Design.find(params[:id])
  # end

  # POST /designs
  # POST /designs.xml
  def create
    @design = Design.new(params[:design])

    respond_to do |format|
      if @design.save
        format.html { redirect_to(@design, :notice => 'Design was successfully created.') }
        format.xml  { render :xml => @design, :status => :created, :location => @design }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @design.errors, :status => :unprocessable_entity }
      end
    end
  end

  # # PUT /designs/1
  # # PUT /designs/1.xml
  # def update
  #   @design = Design.find(params[:id])
  # 
  #   respond_to do |format|
  #     if @design.update_attributes(params[:design])
  #       format.html { redirect_to(@design, :notice => 'Design was successfully updated.') }
  #       format.xml  { head :ok }
  #     else
  #       format.html { render :action => "edit" }
  #       format.xml  { render :xml => @design.errors, :status => :unprocessable_entity }
  #     end
  #   end
  # end
  # 
  # # DELETE /designs/1
  # # DELETE /designs/1.xml
  # def destroy
  #   @design = Design.find(params[:id])
  #   @design.destroy
  # 
  #   respond_to do |format|
  #     format.html { redirect_to(designs_url) }
  #     format.xml  { head :ok }
  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/designs_helper.rb
module DesignsHelper
  
  def highlight_description(description)
    text = description.split(' ')
    result_text = []
    text.each do |t|
      t = content_tag(:span, h(t), :class => 'highlight') if t.downcase == 'design'
      t = content_tag(:span, h(t), :class => 'highlight') if t.downcase.include?('%')
      t = content_tag(:span, h(t), :class => 'highlight') if t.downcase.include?('$')
      t = content_tag(:span, h(t), :class => 'highlight') if t.to_f.to_s == t
      t = content_tag(:span, h(t), :class => 'highlight') if t.to_i.to_s == t
      t = content_tag(:span, h(t), :class => 'highlight') if t.gsub(',','').to_i.to_s == t.gsub(',','')
      result_text << t
    end
    result_text.join(' ')
  end
end

app/views/designs/_design.html.erb
<h1 id="description">
  <%=raw highlight_description(@design.description) %>
</h1>
<%= link_to truncate(@design.source_url), @design.source_url %><br />
<% if @design.tag_list.any? %>
  <% @design.tag_list.each do |tag|%>
    <%= link_to tag, designs_by_tag_path(tag) %>
  <% end %>
<% end %>

app/views/designs/_form.html.erb
<%= form_for(@design) do |f| %>
  <% if @design.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@design.errors.count, "error") %> prohibited this design from being saved:</h2>

      <ul>
      <% @design.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description, raw("What's the <strong>impact</strong> of the design?") %>
    <div class="microcopy">
      We need a number here. Think outcomes. What were you measuring? (Design sold 14 million iPhones.)
    </div>
    <%= f.text_area :description, :style => 'width:80%;height:3em' %>
  </div>
  <div class="field">
    <%= f.label :source_url, "Cite your source." %>
    <div class="microcopy">
      Link to where we can learn more or view the design. (http://yomomma...)
    </div>
    <%= f.text_field :source_url, :style => 'width:90%' %>
  </div>
  <div class="field">
    <%= f.label :tag_list, "Tag it up." %>
    <div class="microcopy">
      Add keywords so we can hook you up with designs you might know. (logo, website, book)
    </div>
    <%= f.text_field :tag_list, :style => 'width:90%' %>
  </div>
  
  <div class="actions" style="text-align:center;">
    <%= f.submit 'Submit', :class => 'button' %>
  </div>
<% end %>

app/views/designs/edit.html.erb
<h1>Editing design</h1>

<%= render 'form' %>

<%= link_to 'Show', @design %> |
<%= link_to 'Back', designs_path %>

app/views/designs/index.html.erb
<%= render @design %>

app/views/designs/new.html.erb
<%= render 'form' %>

app/views/designs/show.html.erb
<%= render @design %>

app/views/designs/tag.html.erb
<% if @designs.any? %>
  <% @design = @designs.choice %>
  <%= render @design %>
<% else %>
  No designs found with the tag "<%= params[:id] %>"
<% end %>

app/views/designs/what.html.erb
<h1 id="description">Design is a process for creatively solving problems.</h1>

<p>Most people tend to associate “design” with visual problems, like a logo or t-shirt. But, this process can also be applied to lots of problems; businesses, services, and big, hairy social problems.</p>

<p>Unfortunately, I think we designers mostly suck at describing what we do. We get caught up in the loosey goosey, magical nature of our process. This helps no one understand what the heck we actually do.</p>

<p>Instead people connect with the outcomes of design. The facts: How did you change things? What problem did you solve? How much money did you make? What did you make better (or worse)?</p>

<p>That’s the goal of this website. Get concrete, get real. What impact did design have.</p>


comfort with ambeguity.
<p>The funny thing is, rarely are the metrics we decide are important define at the beginning of a project

<p>---<br />
<%= link_to 'chap', 'http://chapambrose.com'%><br />
<%= link_to 'Austin Center for Design', 'http://austincenterfordesign.com'%><br />
Class of 2011</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>designdidit.com</title>
  <%= stylesheet_link_tag 'screen', 'application', 'buttons' %>
  <!--[if lt IE 8]>
    <%= stylesheet_link_tag 'ie' %>
  <![endif]-->
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="hd">
      <%= link_to 'add a design', new_design_path %>
      <%= link_to image_tag('ff.png'), root_path, :style => 'float:right' %>
    </div>
    <div id="bd">
      <%= yield %>
    </div>
  </div>
</body>
</html>